-- =============================================================================
-- PostMate — Khởi tạo cơ sở dữ liệu (PostgreSQL)
--
-- DB khớp với config/autoload/local.php ('database' => 'postmate').
-- Tên cột dùng camelCase để khớp với query trong các Mapper (vd createdById,
-- scheduledAt, passwordHash...) — mọi định danh được đặt trong dấu ngoặc kép
-- ("camelCase") để PostgreSQL giữ nguyên hoa/thường, khớp với cách
-- Laminas\Db tự động quote identifier khi build câu lệnh.
-- Nguồn: docs/PHAN_TICH_HE_THONG.md (mục 2 - CSDL, mục 6.5 - bổ sung Graph API).
--
-- Cách dùng (PostgreSQL, 2 bước — không thể gộp CREATE DATABASE vào cùng
-- 1 kết nối với phần còn lại của script):
--   1) createdb -U postgres postmate
--      (hoặc: psql -U postgres -c "CREATE DATABASE postmate ENCODING 'UTF8';")
--   2) psql -U postgres -d postmate -f data/db/postmate.sql
--
-- Tài khoản đăng nhập mẫu:  username = admin   password = admin123
-- =============================================================================

-- -----------------------------------------------------------------------------
-- users — Người dùng hệ thống (module User)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "users" (
    "id"           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "username"     VARCHAR(100)    NOT NULL,
    "email"        VARCHAR(190)    NOT NULL,
    "passwordHash" VARCHAR(255)    NOT NULL,
    "fullName"     VARCHAR(190)    DEFAULT NULL,
    "avatarUrl"    VARCHAR(255)    DEFAULT NULL,
    "role"         VARCHAR(20)     NOT NULL DEFAULT 'member',   -- admin | member | viewer
    "plan"         VARCHAR(50)     DEFAULT NULL,
    "fbUserId"     VARCHAR(64)     DEFAULT NULL,
    "status"       SMALLINT        NOT NULL DEFAULT 1,          -- 1 active, 2 inactive, 3 locked
    "createdAt"    BIGINT          DEFAULT NULL,
    "updatedAt"    BIGINT          DEFAULT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_users_username" UNIQUE ("username"),
    CONSTRAINT "uq_users_email" UNIQUE ("email")
);
CREATE INDEX IF NOT EXISTS "idx_users_status" ON "users" ("status");

-- -----------------------------------------------------------------------------
-- servers — Máy chủ chạy Chrome instance (module Infra)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "servers" (
    "id"            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "name"          VARCHAR(190)    NOT NULL,           -- Server 01/02/03
    "ipAddress"     VARCHAR(45)     DEFAULT NULL,
    "status"        SMALLINT        NOT NULL DEFAULT 1, -- 1 online, 2 offline
    "cpuUsage"      REAL            DEFAULT NULL,
    "ramUsage"      REAL            DEFAULT NULL,
    "maxInstances"  INTEGER         NOT NULL DEFAULT 0,
    "createdById"   BIGINT          DEFAULT NULL,
    "createdAt"     BIGINT          DEFAULT NULL,
    "modifiedAt"    BIGINT          DEFAULT NULL,
    PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "idx_servers_status" ON "servers" ("status");

-- -----------------------------------------------------------------------------
-- proxies — IP/Proxy gán cho browser_profiles (module Infra)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "proxies" (
    "id"          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "ip"          VARCHAR(45)     NOT NULL,
    "country"     VARCHAR(10)     DEFAULT NULL,         -- VN...
    "type"        SMALLINT        NOT NULL DEFAULT 1,   -- 1 residential, 2 datacenter, 3 mobile
    "status"      SMALLINT        NOT NULL DEFAULT 1,   -- 1 active, 2 dead
    "createdById" BIGINT          DEFAULT NULL,
    "createdAt"   BIGINT          DEFAULT NULL,
    "modifiedAt"  BIGINT          DEFAULT NULL,
    PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "idx_proxies_status" ON "proxies" ("status");

-- -----------------------------------------------------------------------------
-- ai_agents — AI Agent hỗ trợ soạn nội dung (module AI)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "ai_agents" (
    "id"          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "name"        VARCHAR(190)    NOT NULL,
    "status"      SMALLINT        NOT NULL DEFAULT 1,   -- 1 active, 2 idle
    "model"       VARCHAR(190)    DEFAULT NULL,
    "config"      TEXT            DEFAULT NULL,         -- JSON
    "createdById" BIGINT          DEFAULT NULL,
    "createdAt"   BIGINT          DEFAULT NULL,
    "modifiedAt"  BIGINT          DEFAULT NULL,
    PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "idx_ai_agents_status" ON "ai_agents" ("status");

-- -----------------------------------------------------------------------------
-- browser_profiles — Chrome instance chống phát hiện (module Infra)
-- facebookAccountId gắn 1-1 với facebook_accounts; FK được thêm sau khi
-- facebook_accounts được tạo (tránh phụ thuộc vòng khi khởi tạo).
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "browser_profiles" (
    "id"                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "code"               VARCHAR(100)    DEFAULT NULL,        -- Chrome #01
    "profileName"        VARCHAR(190)    DEFAULT NULL,        -- khanh01
    "profileId"          INTEGER         DEFAULT NULL,
    "serverId"           BIGINT          DEFAULT NULL,
    "proxyId"            BIGINT          DEFAULT NULL,
    "facebookAccountId"  BIGINT          DEFAULT NULL,
    "status"             SMALLINT        NOT NULL DEFAULT 2,  -- 1 running, 2 stopped, 3 offline
    "mode"               SMALLINT        NOT NULL DEFAULT 1,  -- 1 headless, 2 gui
    "chromeVersion"      VARCHAR(50)     DEFAULT NULL,
    "os"                 VARCHAR(100)    DEFAULT NULL,
    "userAgent"          TEXT            DEFAULT NULL,
    "fingerprintJson"    TEXT            DEFAULT NULL,        -- JSON: canvas/webgl/fonts/timezone/screen
    "cpuPercent"         REAL            DEFAULT NULL,
    "ramMb"              INTEGER         DEFAULT NULL,
    "startedAt"          TIMESTAMP       DEFAULT NULL,
    "lastActiveAt"       TIMESTAMP       DEFAULT NULL,
    "uptimeMinutes"      INTEGER         DEFAULT NULL,
    "createdById"        BIGINT          DEFAULT NULL,
    "createdAt"          BIGINT          DEFAULT NULL,
    "modifiedAt"         BIGINT          DEFAULT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "fk_browser_profiles_server" FOREIGN KEY ("serverId")
        REFERENCES "servers" ("id") ON DELETE SET NULL,
    CONSTRAINT "fk_browser_profiles_proxy" FOREIGN KEY ("proxyId")
        REFERENCES "proxies" ("id") ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS "idx_browser_profiles_server" ON "browser_profiles" ("serverId");
CREATE INDEX IF NOT EXISTS "idx_browser_profiles_proxy" ON "browser_profiles" ("proxyId");
CREATE INDEX IF NOT EXISTS "idx_browser_profiles_fb_account" ON "browser_profiles" ("facebookAccountId");
CREATE INDEX IF NOT EXISTS "idx_browser_profiles_status" ON "browser_profiles" ("status");

-- -----------------------------------------------------------------------------
-- facebook_accounts — Tài khoản Facebook dùng để đăng (module Facebook)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "facebook_accounts" (
    "id"                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "ownerUserId"       BIGINT          NOT NULL,
    "displayName"       VARCHAR(190)    DEFAULT NULL,
    "email"             VARCHAR(190)    DEFAULT NULL,
    "avatarUrl"         VARCHAR(255)    DEFAULT NULL,
    "fbUserId"          VARCHAR(64)     DEFAULT NULL,        -- id thật từ Graph API /me (OAuth Facebook Login)
    "userAccessToken"   TEXT            DEFAULT NULL,        -- long-lived user access token, mã hóa at-rest
    "browserProfileId"  BIGINT          DEFAULT NULL,
    "status"            SMALLINT        NOT NULL DEFAULT 1,  -- 1 active, 2 inactive, 3 checkpoint
    "accountRole"       VARCHAR(50)     DEFAULT NULL,        -- Quản trị viên | Biên tập viên (màn Cài đặt > Facebook)
    "isPrimary"         SMALLINT        NOT NULL DEFAULT 0,  -- tài khoản Chính
    "expiresAt"         TIMESTAMP       DEFAULT NULL,        -- hạn quyền/token kết nối
    "lastLoginAt"       TIMESTAMP       DEFAULT NULL,
    "lastLoginIp"       VARCHAR(45)     DEFAULT NULL,
    "device"            VARCHAR(190)    DEFAULT NULL,
    "userAgent"         TEXT            DEFAULT NULL,
    "capabilities"      TEXT            DEFAULT NULL,        -- JSON: post/upload/comment/reply/inbox
    "createdAt"         BIGINT          DEFAULT NULL,
    "modifiedAt"        BIGINT          DEFAULT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "fk_fb_accounts_owner" FOREIGN KEY ("ownerUserId")
        REFERENCES "users" ("id") ON DELETE CASCADE,
    CONSTRAINT "fk_fb_accounts_browser_profile" FOREIGN KEY ("browserProfileId")
        REFERENCES "browser_profiles" ("id") ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS "idx_fb_accounts_owner" ON "facebook_accounts" ("ownerUserId");
CREATE INDEX IF NOT EXISTS "idx_fb_accounts_browser_profile" ON "facebook_accounts" ("browserProfileId");
CREATE INDEX IF NOT EXISTS "idx_fb_accounts_status" ON "facebook_accounts" ("status");
CREATE INDEX IF NOT EXISTS "idx_fb_accounts_fbuserid" ON "facebook_accounts" ("fbUserId");

-- Đóng vòng quan hệ 1-1 browser_profiles <-> facebook_accounts
ALTER TABLE "browser_profiles"
    ADD CONSTRAINT "fk_browser_profiles_fb_account" FOREIGN KEY ("facebookAccountId")
        REFERENCES "facebook_accounts" ("id") ON DELETE SET NULL;

-- -----------------------------------------------------------------------------
-- cookies — Phiên đăng nhập Facebook (module Facebook)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "cookies" (
    "id"                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "code"               VARCHAR(100)    DEFAULT NULL,       -- ck_01a7f9c3...d9b2
    "facebookAccountId"  BIGINT          NOT NULL,
    "browserProfileId"   BIGINT          DEFAULT NULL,
    "sizeKb"             REAL            DEFAULT NULL,
    "status"             SMALLINT        NOT NULL DEFAULT 1, -- 1 valid, 2 expiring, 3 invalid
    "expiresAt"          DATE            DEFAULT NULL,
    "lastLoginAt"        TIMESTAMP       DEFAULT NULL,
    "lastLoginIp"        VARCHAR(45)     DEFAULT NULL,
    "device"             VARCHAR(190)    DEFAULT NULL,
    "userAgent"          TEXT            DEFAULT NULL,
    "cookieBlob"         TEXT            DEFAULT NULL,       -- nội dung cookie (mã hóa at-rest)
    "createdAt"          BIGINT          DEFAULT NULL,
    "modifiedAt"         BIGINT          DEFAULT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "fk_cookies_fb_account" FOREIGN KEY ("facebookAccountId")
        REFERENCES "facebook_accounts" ("id") ON DELETE CASCADE,
    CONSTRAINT "fk_cookies_browser_profile" FOREIGN KEY ("browserProfileId")
        REFERENCES "browser_profiles" ("id") ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS "idx_cookies_fb_account" ON "cookies" ("facebookAccountId");
CREATE INDEX IF NOT EXISTS "idx_cookies_browser_profile" ON "cookies" ("browserProfileId");
CREATE INDEX IF NOT EXISTS "idx_cookies_status" ON "cookies" ("status");

-- -----------------------------------------------------------------------------
-- meta_app_credentials — Cấu hình Meta App (mục 6.5, kênh Graph API)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "meta_app_credentials" (
    "id"                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "appId"              VARCHAR(190)    NOT NULL,
    "appSecret"          VARCHAR(255)    DEFAULT NULL,        -- mã hóa at-rest
    "systemUserToken"    TEXT            DEFAULT NULL,        -- mã hóa at-rest, token dài hạn
    "createdById"        BIGINT          DEFAULT NULL,
    "createdAt"          BIGINT          DEFAULT NULL,
    "modifiedAt"         BIGINT          DEFAULT NULL,
    PRIMARY KEY ("id")
);

-- -----------------------------------------------------------------------------
-- fanpages — Fanpage do tài khoản Facebook quản lý (module Facebook)
-- Bổ sung pageAccessToken/tokenExpiresAt/apiEnabled theo mục 6.5 (Graph API).
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "fanpages" (
    "id"                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "fbPageId"           VARCHAR(64)     DEFAULT NULL,
    "name"               VARCHAR(190)    NOT NULL,
    "category"           VARCHAR(190)    DEFAULT NULL,
    "url"                VARCHAR(255)    DEFAULT NULL,
    "facebookAccountId"  BIGINT          NOT NULL,
    "browserProfileId"   BIGINT          DEFAULT NULL,
    "likesCount"         INTEGER         DEFAULT NULL,
    "followersCount"     INTEGER         DEFAULT NULL,
    "status"             SMALLINT        NOT NULL DEFAULT 1,  -- 1 active, 2 need_relogin, 3 inactive
    "canPost"            SMALLINT        NOT NULL DEFAULT 1,
    "capabilities"       TEXT            DEFAULT NULL,        -- JSON: post/comment/upload/reply/inbox
    "lastPostAt"         TIMESTAMP       DEFAULT NULL,
    "pageAccessToken"    TEXT            DEFAULT NULL,        -- mã hóa at-rest, token đăng qua Graph API
    "tokenExpiresAt"     TIMESTAMP       DEFAULT NULL,
    "apiEnabled"         SMALLINT        NOT NULL DEFAULT 0,
    "createdAt"          BIGINT          DEFAULT NULL,
    "modifiedAt"         BIGINT          DEFAULT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "fk_fanpages_fb_account" FOREIGN KEY ("facebookAccountId")
        REFERENCES "facebook_accounts" ("id") ON DELETE CASCADE,
    CONSTRAINT "fk_fanpages_browser_profile" FOREIGN KEY ("browserProfileId")
        REFERENCES "browser_profiles" ("id") ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS "idx_fanpages_fb_account" ON "fanpages" ("facebookAccountId");
CREATE INDEX IF NOT EXISTS "idx_fanpages_browser_profile" ON "fanpages" ("browserProfileId");
CREATE INDEX IF NOT EXISTS "idx_fanpages_status" ON "fanpages" ("status");

-- -----------------------------------------------------------------------------
-- posts — Bài viết / lịch đăng (module Posting)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "posts" (
    "id"               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "title"            VARCHAR(500)    DEFAULT NULL,
    "content"          TEXT            DEFAULT NULL,
    "contentType"      SMALLINT        NOT NULL DEFAULT 1,      -- 1 text,2 image,3 video,4 link,5 poll
    "fanpageId"        BIGINT          DEFAULT NULL,
    "browserProfileId" BIGINT          DEFAULT NULL,
    "aiAgentId"        BIGINT          DEFAULT NULL,
    "status"           SMALLINT        NOT NULL DEFAULT 1,      -- 1 draft,2 scheduled,3 processing,4 published,5 failed,6 expired,7 deleted
    "channel"          SMALLINT        NOT NULL DEFAULT 1,      -- 1 graph_api, 2 browser
    "scheduledAt"      TIMESTAMP       DEFAULT NULL,
    "publishedAt"      TIMESTAMP       DEFAULT NULL,
    "attemptCount"     INTEGER         NOT NULL DEFAULT 0,
    "maxAttempts"      INTEGER         NOT NULL DEFAULT 3,
    "repeatRule"       VARCHAR(255)    DEFAULT NULL,
    "fbPostId"         VARCHAR(128)    DEFAULT NULL,
    "note"             VARCHAR(255)    DEFAULT NULL,
    "options"          TEXT            DEFAULT NULL,            -- JSON: autoShortenLink/disableCommentNotif/autoShare
    "createdById"      BIGINT          DEFAULT NULL,
    "createdAt"        BIGINT          DEFAULT NULL,
    "modifiedById"     BIGINT          DEFAULT NULL,
    "modifiedAt"       BIGINT          DEFAULT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "fk_posts_fanpage" FOREIGN KEY ("fanpageId")
        REFERENCES "fanpages" ("id") ON DELETE SET NULL,
    CONSTRAINT "fk_posts_browser_profile" FOREIGN KEY ("browserProfileId")
        REFERENCES "browser_profiles" ("id") ON DELETE SET NULL,
    CONSTRAINT "fk_posts_ai_agent" FOREIGN KEY ("aiAgentId")
        REFERENCES "ai_agents" ("id") ON DELETE SET NULL,
    CONSTRAINT "fk_posts_owner" FOREIGN KEY ("createdById")
        REFERENCES "users" ("id") ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS "idx_posts_owner" ON "posts" ("createdById");
CREATE INDEX IF NOT EXISTS "idx_posts_status" ON "posts" ("status");
CREATE INDEX IF NOT EXISTS "idx_posts_scheduledAt" ON "posts" ("scheduledAt");
CREATE INDEX IF NOT EXISTS "idx_posts_fanpage" ON "posts" ("fanpageId");
CREATE INDEX IF NOT EXISTS "idx_posts_browser_profile" ON "posts" ("browserProfileId");
CREATE INDEX IF NOT EXISTS "idx_posts_ai_agent" ON "posts" ("aiAgentId");
CREATE INDEX IF NOT EXISTS "idx_posts_owner_status" ON "posts" ("createdById", "status");

-- -----------------------------------------------------------------------------
-- post_media — Ảnh/video đính kèm bài viết (module Posting)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "post_media" (
    "id"          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "postId"      BIGINT          NOT NULL,
    "type"        SMALLINT        NOT NULL DEFAULT 1,           -- 1 image, 2 video
    "url"         VARCHAR(500)    NOT NULL,
    "storagePath" VARCHAR(500)    DEFAULT NULL,
    "orderIndex"  INTEGER         NOT NULL DEFAULT 0,
    "createdAt"   BIGINT          DEFAULT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "fk_post_media_post" FOREIGN KEY ("postId")
        REFERENCES "posts" ("id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "idx_post_media_post" ON "post_media" ("postId");

-- -----------------------------------------------------------------------------
-- post_execution_logs — Timeline thực thi bài viết (màn Lịch đăng)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "post_execution_logs" (
    "id"           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "postId"       BIGINT          NOT NULL,
    "step"         VARCHAR(190)    NOT NULL,        -- Mở trình duyệt/Truy cập Facebook/Đi tới fanpage/...
    "status"       SMALLINT        NOT NULL DEFAULT 1, -- 1 success, 2 failed
    "durationSec"  INTEGER         DEFAULT NULL,
    "loggedAt"     TIMESTAMP       DEFAULT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "fk_post_exec_logs_post" FOREIGN KEY ("postId")
        REFERENCES "posts" ("id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "idx_post_exec_logs_post" ON "post_execution_logs" ("postId");

-- -----------------------------------------------------------------------------
-- post_metrics — Hiệu suất bài viết, đồng bộ định kỳ từ Facebook (màn Bài viết)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "post_metrics" (
    "postId"      BIGINT          NOT NULL,
    "likes"       INTEGER         NOT NULL DEFAULT 0,
    "comments"    INTEGER         NOT NULL DEFAULT 0,
    "shares"      INTEGER         NOT NULL DEFAULT 0,
    "reach"       INTEGER         NOT NULL DEFAULT 0,
    "engagement"  INTEGER         NOT NULL DEFAULT 0,
    "saves"       INTEGER         NOT NULL DEFAULT 0,
    "updatedAt"   BIGINT          DEFAULT NULL,
    PRIMARY KEY ("postId"),
    CONSTRAINT "fk_post_metrics_post" FOREIGN KEY ("postId")
        REFERENCES "posts" ("id") ON DELETE CASCADE
);

-- -----------------------------------------------------------------------------
-- activity_logs — Nhật ký hoạt động toàn hệ thống (Dashboard)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "activity_logs" (
    "id"          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "userId"      BIGINT          DEFAULT NULL,
    "entityRef"   VARCHAR(190)    DEFAULT NULL,        -- vd post:123, fanpage:45
    "type"        VARCHAR(100)    DEFAULT NULL,         -- Đăng bài/Khởi động Chrome/Refresh cookie/Tạo lịch...
    "message"     TEXT            DEFAULT NULL,
    "level"       SMALLINT        NOT NULL DEFAULT 1,   -- 1 info, 2 success, 3 warning, 4 error
    -- Bổ sung cho màn Nhật ký hệ thống (diarysetting.png)
    "actorRole"   VARCHAR(20)     DEFAULT NULL,        -- vai trò người thao tác lúc ghi log (admin/member/viewer)
    "objectName"  VARCHAR(190)    DEFAULT NULL,        -- tên đối tượng (vd Shoes Store)
    "objectType"  VARCHAR(50)     DEFAULT NULL,        -- loại đối tượng (vd Trang Facebook, Nhóm...)
    "ipAddress"   VARCHAR(45)     DEFAULT NULL,        -- IP thao tác
    "device"      VARCHAR(190)    DEFAULT NULL,        -- Chrome / Windows...
    "createdAt"   BIGINT          DEFAULT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "fk_activity_logs_user" FOREIGN KEY ("userId")
        REFERENCES "users" ("id") ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS "idx_activity_logs_user" ON "activity_logs" ("userId");
CREATE INDEX IF NOT EXISTS "idx_activity_logs_level" ON "activity_logs" ("level");
CREATE INDEX IF NOT EXISTS "idx_activity_logs_created" ON "activity_logs" ("createdAt");

-- -----------------------------------------------------------------------------
-- settings — Cấu hình theo user (màn Cài đặt)
-- Bổ sung preferredChannel/allowBrowserFallback theo mục 6.5 (Graph API).
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "settings" (
    "userId"               BIGINT          NOT NULL,
    "language"             VARCHAR(20)     DEFAULT 'vi',       -- Tiếng Việt
    "timezone"             VARCHAR(50)     DEFAULT 'Asia/Ho_Chi_Minh',
    "dateFormat"           VARCHAR(20)     DEFAULT 'DD/MM/YYYY', -- Định dạng ngày hiển thị (màn Tài khoản)
    "themeMode"            VARCHAR(20)     NOT NULL DEFAULT 'light',    -- light | dark | system (màn Cài đặt chung)
    "displayDensity"       VARCHAR(20)     NOT NULL DEFAULT 'standard', -- compact | standard | comfortable
    "defaultFanpageId"     BIGINT          DEFAULT NULL,
    "defaultContentType"   SMALLINT        DEFAULT 1,          -- xem PostConst::CONTENT_TYPE_*
    "defaultStatus"        SMALLINT        DEFAULT 2,          -- xem PostConst::STATUS_*
    "defaultPostTime"      TIME            DEFAULT NULL,
    "autoShortenLink"      SMALLINT        NOT NULL DEFAULT 0,
    "autoSaveDraft"        SMALLINT        NOT NULL DEFAULT 0,
    "showAiSuggestions"    SMALLINT        NOT NULL DEFAULT 1,
    "confirmBeforePost"    SMALLINT        NOT NULL DEFAULT 1,
    -- Tùy chọn hệ thống chung (màn Cài đặt chung / allsetting.png)
    "confirmBeforeDelete"  SMALLINT        NOT NULL DEFAULT 1, -- Xác nhận trước khi xóa
    "autoSaveChanges"      SMALLINT        NOT NULL DEFAULT 1, -- Tự động lưu thay đổi
    "notificationSound"    SMALLINT        NOT NULL DEFAULT 0, -- Phát âm thanh thông báo
    "showQuickHints"       SMALLINT        NOT NULL DEFAULT 1, -- Hiển thị gợi ý nhanh
    "performanceTracking"  SMALLINT        NOT NULL DEFAULT 0, -- Theo dõi hiệu suất
    "preferredChannel"     SMALLINT        NOT NULL DEFAULT 1, -- 1 graph_api, 2 browser
    "allowBrowserFallback" SMALLINT        NOT NULL DEFAULT 1,
    "storageUsed"          BIGINT          DEFAULT 0,
    "storageLimit"         BIGINT          DEFAULT 0,
    "appVersion"           VARCHAR(20)     DEFAULT NULL,
    "lastBackupAt"         TIMESTAMP       DEFAULT NULL,
    "updatedAt"            BIGINT          DEFAULT NULL,
    PRIMARY KEY ("userId"),
    CONSTRAINT "fk_settings_user" FOREIGN KEY ("userId")
        REFERENCES "users" ("id") ON DELETE CASCADE,
    CONSTRAINT "fk_settings_default_fanpage" FOREIGN KEY ("defaultFanpageId")
        REFERENCES "fanpages" ("id") ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS "idx_settings_default_fanpage" ON "settings" ("defaultFanpageId");

-- -----------------------------------------------------------------------------
-- Seed: tài khoản đăng nhập mẫu (admin / admin123) + dữ liệu mẫu liên quan
-- passwordHash = password_hash('admin123', PASSWORD_BCRYPT)
-- -----------------------------------------------------------------------------
DO $$
DECLARE
    v_admin_id BIGINT;
BEGIN
    INSERT INTO "users"
        ("username", "email", "passwordHash", "fullName", "role", "status", "createdAt")
    VALUES
        ('admin', 'admin@postmate.local',
         '$2y$10$DHKY.UI9RrnezrIW3rgw/.MMz80MCTdIWoFMXdXMUtixJJA6MM.ja',
         'Administrator', 'admin', 1, EXTRACT(EPOCH FROM NOW())::BIGINT)
    ON CONFLICT ("username") DO NOTHING;

    SELECT "id" INTO v_admin_id FROM "users" WHERE "username" = 'admin' LIMIT 1;

    -- Seed: tài khoản Facebook mẫu (màn Cài đặt > Facebook — facebooksetting.png)
    -- Ngày hạn tính tương đối theo NOW() để luôn hiển thị "Còn N ngày" hợp lý bất kể chạy lúc nào.
    IF NOT EXISTS (SELECT 1 FROM "facebook_accounts" WHERE "ownerUserId" = v_admin_id) THEN
        INSERT INTO "facebook_accounts"
            ("ownerUserId", "displayName", "email", "status", "accountRole", "isPrimary",
             "expiresAt", "lastLoginAt", "createdAt")
        VALUES
            (v_admin_id, 'Khánh Nguyễn', '100012345678901', 1, 'Quản trị viên', 1,
             NOW() + INTERVAL '178 days', NOW() - INTERVAL '10 days', EXTRACT(EPOCH FROM NOW())::BIGINT),
            (v_admin_id, 'Linh Mai', '100098765432109', 1, 'Biên tập viên', 0,
             NOW() + INTERVAL '176 days', NOW() - INTERVAL '12 days', EXTRACT(EPOCH FROM NOW())::BIGINT),
            (v_admin_id, 'Hoàng Minh', '1000111222333344', 2, 'Biên tập viên', 0,
             NOW() - INTERVAL '30 days', NOW() - INTERVAL '40 days', EXTRACT(EPOCH FROM NOW())::BIGINT);
    END IF;

    -- Seed: nhật ký hoạt động mẫu (màn Cài đặt > Nhật ký hệ thống — diarysetting.png)
    IF NOT EXISTS (SELECT 1 FROM "activity_logs" WHERE "userId" = v_admin_id) THEN
        INSERT INTO "activity_logs"
            ("userId", "entityRef", "type", "message", "level", "actorRole",
             "objectName", "objectType", "ipAddress", "device", "createdAt")
        VALUES
            (v_admin_id, 'post:1', 'Đăng bài viết', 'BST giày thể thao mới 2025', 2, 'admin',
             'Shoes Store', 'Trang Facebook', '123.45.67.89', 'Chrome / Windows',
             EXTRACT(EPOCH FROM TIMESTAMP '2025-05-29 09:35:21')::BIGINT),
            (v_admin_id, 'post:2', 'Cập nhật bài viết', 'Flash sale cuối tuần – Giảm 50%', 1, 'member',
             'Fashion Store', 'Trang Facebook', '113.160.22.15', 'Chrome / macOS',
             EXTRACT(EPOCH FROM TIMESTAMP '2025-05-29 09:22:10')::BIGINT),
            (v_admin_id, 'post:3', 'Lên lịch bài viết', 'Bí quyết chăm sóc da mùa hè – Thời gian: 30/05/2025 10:00', 1, 'member',
             'Cosmetics Store', 'Trang Facebook', '171.244.10.33', 'Firefox / Windows',
             EXTRACT(EPOCH FROM TIMESTAMP '2025-05-29 09:15:45')::BIGINT),
            (v_admin_id, 'post:4', 'Xóa bài viết', 'Không gian sống hiện đại (ID: 1234567890)', 3, 'admin',
             'Home & Living', 'Trang Facebook', '123.45.67.89', 'Chrome / Windows',
             EXTRACT(EPOCH FROM TIMESTAMP '2025-05-29 09:50:12')::BIGINT),
            (v_admin_id, 'member:5', 'Thêm thành viên', 'Thêm thành viên: Minh Anh — Vai trò: Editor', 2, 'member',
             'Nhóm Marketing', 'Nhóm', '171.244.10.33', 'Firefox / Windows',
             EXTRACT(EPOCH FROM TIMESTAMP '2025-05-29 18:05:07')::BIGINT),
            (v_admin_id, 'settings:1', 'Thay đổi cài đặt', 'Bật: Đăng ngẫu nhiên trong khung giờ', 1, 'admin',
             'Cài đặt chung', 'Hệ thống', '123.45.67.89', 'Chrome / Windows',
             EXTRACT(EPOCH FROM TIMESTAMP '2025-05-28 14:30:55')::BIGINT);
    END IF;
END $$;
